### ISSUE TITLE
OkHttp inspector hangs on big uploads

### ISSUE THREAD

**Issue by evgeny-sureev** [facebook/stetho#329]
My app uploads photos taken from camera. If upload request appears on log, Chrome hangs completely. I think this happens because inspector tries to dump raw jpeg content to Headers tab.

**Comment by jasta** [comment]
This is due to a very unfortunate limitation in the inspector protocol which appears to require that we serialize request payloads as UTF-8 strings and upload them to the UI.  I know of no way around this other than to perhaps upgrade to a newer version of the protocol (which I haven't evaluated in ~6 months) or to simply detect large payloads and omit them when reporting the request.

I tried for a while to figure out what current Chrome upstream does when uploading large images but for reasons I forget now couldn't seem to repro this issue.  If you're feeling motivated, you could raelly help speed this up by connecting Chrome for Android to Chrome on your PC/laptop (chrome://inspect just like with Stetho, find your Chrome for Android instance and click Inspect), then try to get Chrome for Android to upload a very large payload to a server and capture what the inspector does.  In either case (it does what you want or not) could you take a screenshot for us and we'll see what we can do?

**Comment by evgeny-sureev** [comment]
It seems that Chrome omits large payloads:

![screenshot](https://cloud.githubusercontent.com/assets/7701455/12440402/37a60124-bf4c-11e5-827a-4028b0cc491b.png)

This is from stetho with image displayed as raw content:

![example](https://cloud.githubusercontent.com/assets/7701455/12440473/e259fad0-bf4c-11e5-84fb-25d0a1313f74.jpg)

With small sized images inspector just slow down, so I am able to capture screenshot. When image size exceed 1 Mb, inspector stop responding.

**Comment by jasta** [comment]
I think the right thing to do then would be to detect large payloads and simply omit them from the payload string.  If you're interested in taking a crack at this, it should be a simple matter of applying this heuristic in `NetworkEventReporterImpl.java:readBodyAsString`.  Because this method sees the decompressed body, it should be safe to simply look for binary and/or very large payloads and replace those payloads with something else.

Also note that it's possible to do an even better job filtering this out for `StethoInterceptor` because it can detect a multi-part request body and inspect the content-type of each part individually to determine what it should report.  But if you don't do this carefully you will end up causing the "request size" field to not be computed correctly.

**Comment by jasta** [comment]
Closing due to inactivity, though I'm still very interested in having this issue solved.  I just doubt I'll personally have time unless I hit this issue in one of my apps (which, I guess, is Facebook for Android hehe)

**Comment by sudhirkhanger** [comment]
How are you not hitting this issue? Anytime the POST request fails the inspector will try to load image in it and freeze.

**Comment by thebehera** [comment]
i believe i have fixed the bug here, https://github.com/facebook/stetho/pull/564 should fix it

**Comment by DavidJRobertson** [comment]
I am still encountering this issue with image uploads using version 1.5.1.
